/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: CommunicationNode (https://sketchfab.com/Starven38)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/personal-computer-aa398650fe6e4baa8771c71266d842f4
Title: Personal Computer
*/

import React, { useRef } from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'

const DemoComputer =(props)=> {
  const { nodes, materials } = useGLTF('/models/personal_computer.glb')
  const txt = useVideoTexture(props.texture?props.texture:'textures/project/project1.mp4')
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_PC_0.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_LightMat_0.geometry}
              material={materials.LightMat}
            />
            <mesh
             
              geometry={nodes.Cube_Screen_0.geometry}
            //   material={materials.Screen} 
            >
                <meshBasicMaterial map={txt}  toneMapped={false} />
                </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube_Keyboard_0.geometry}
              material={materials.Keyboard}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/personal_computer.glb')
export default DemoComputer;